name: sensor_converter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.3.1
  csv: ^5.0.2
  http: ^1.1.0
  h3_dart: ^0.6.2
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
